// No need for 'use client' directive here as the layout is part of the server-side code

import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
// import { useEffect } from "react";
// import Modal from "react-modal";

// Export metadata as it is part of server-side rendering
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   // Ensure Modal is set to use #__next as the app element for accessibility
  //   Modal.setAppElement("#__next");
  // }, []);

  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,500&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className="bg-[#F8F8FA]" id="__next">
        {children}
      </body>
    </html>
  );
}
